### PR TITLE
Rename LinkMonitor to OnlineResourceMonitor

### PR DESCRIPTION
**Pull request by akashisama**
Should be merged at same time as chef PRs: https://github.com/aodn/chef-private/pull/2300 and https://github.com/aodn/chef/pull/502

Compiles and runs but I haven't tested the actual monitor functionality yet.

### CODE REVIEW

**Comment by julian1** [comment]
Can we wait to get the other logging code in before merging this? Hopefully I'll get the PR up today.

**Comment by jonescc** [comment]
Need to resolve merge conflicts now that @julian1's changes have been merged.

**Comment by julian1** [comment]
Is it possible to squash the commits into one?

**Comment by akashisama** [comment]
@julian1 yep

**Comment by julian1** [comment]
Have you tested this?

**Comment by julian1** [comment]
I've resolved conflicts and merged, https://github.com/aodn/core-geonetwork/pull/79

**Pull request closed without merging**
