### PR TITLE
Remove citation details field from search results.  It was never bein…

### PR DESCRIPTION
**Pull request by jonescc**
…g populated and is not required.

### CODE REVIEW

**Comment by julian1** [comment]
Is this an opportunity to get rid of the gitsubmodule link to schema-plugins?

**Comment by julian1** [comment]
I'm also wondering why we have to change core-geonetwork, to manipulate fields that are specific to our content.

**Comment by jonescc** [comment]
@julian1, I don't think we should stop using git submodule links under this pr.  Need to relook at the deployment process for schema plugins to do that.  This should be a backlog item, or part of work specifically targeted to do that.

Yes, I agree that content specific dump fields would be better being specified elsewhere - e.g. the schem plugins, but this would require changes to GeoNetwork so would also need to be separate to cleaning up entries that have been made here previously.

**Comment by julian1** [comment]
Mixing up emii specific content and java code, is terrible separation of concerns.

**Pull request merged**
